server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ha-jinwoo/spring-cloud-config
          #          username:  # private 인 경우
          #          password:  # private 인 경우